language: python

python:
  - "3.7"

install:
  - pip install nala

script:
  - make test
  - make library
  - make install PREFIX=root

after_success:
  - bash <(curl -s https://codecov.io/bash) -X coveragepy
